[package]
name = "rust-wiki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
home = "0.5.9"
lazy_static = "1.5.0"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
rand = "0.8.5"

[lib]
# Way too slow to run
doctest = false
